[independent, -1, [
	["Land_HelipadEmpty_F", 25, "Logistics"],
        ["Land_Cargo20_EMP_Training_F", 50, "Logistics"],
        ["Land_Cargo_Tower_V1_F", 75,"Military"],
        ["Land_DragonsTeeth_01_4x2_new_redwhite_F", 10,"Obstructions"],
        ["Land_BagBunker_Small_F", 10,"Military"],
        ["Land_BagBunker_Large_F", 20,"Military"],
        ["Land_BagBunker_Tower_F", 20,"Military"],
        ["Land_LampAirport_F", 15,"Airport"],
        ["Land_LampHarbour_F", 6,"Airport"],
        ["Land_TentHangar_V1_F", 30,"Airport"],
        ["Land_BagFence_Corner_F", 3,"Sandbags"],
        ["Land_BagFence_End_F", 2,"Sandbags"],
        ["Land_BagFence_Long_F", 4,"Sandbags"],
        ["Land_BagFence_Round_F", 4,"Sandbags"],
        ["Land_BagFence_Short_F", 3,"Sandbags"],
        ["Land_SandbagBarricade_01_half_F", 4,"Sandbags"],
        ["Land_SandbagBarricade_01_F", 5,"Sandbags"],
        ["Land_SandbagBarricade_01_hole_F", 5,"Sandbags"],
        ["Land_HBarrier_3_lxWS", 10,"Hesco's"],
        ["Land_HBarrier_5_lxWS", 15,"Hesco's"],
        ["Land_HBarrier_1_lxWS", 5,"Hesco's"],
        ["Land_HBarrierWall_corridor_lxWS", 25,"Hesco's"],
        ["Land_HBarrierWall_corner_lxWS", 20,"Hesco's"],
        ["Land_HBarrierWall4_lxWS", 25,"Hesco's"],
        ["Land_HBarrierWall6_lxWS", 30,"Hesco's"],
        ["Land_HBarrierTower_lxWS", 40,"Hesco's"],
        ["Land_Plank_01_4m_F", 3,"Misc"],
        ["Land_Plank_01_8m_F", 5,"Misc"],
        ["Land_Obstacle_Ramp_F", 5,"Misc"],
        ["Land_Obstacle_Pass_F", 8,"Misc"],
        ["Land_Medevac_house_V1_F", 35,"Military"],
        ["Land_Cargo_Patrol_V1_F", 30,"Military"],
        ["Land_Razorwire_F", 4,"Obstructions"],
        ["Land_ConcreteHedgehog_01_F", 3,"Obstructions"],
        ["Wire", 4,"Obstructions"],
        ["Land_CampingChair_V2_F", 2,"Misc"],
        ["Land_Campfire_F", 3,"Misc"],
        ["Land_LampStreet_02_triple_F", 10,"Misc"],
        ["Land_CampingTable_small_F", 3,"Misc"]]] call ace_fortify_fnc_registerObjects;